matrix:
  include:
    - os: linux
      dist: xenial
      jdk: openjdk10
    - os: osx
      jdk: openjdk10
    - os: windows

language: shell

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      choco install jdk11 -params 'installdir=c:\\java11';
      export JAVA_HOME=/c/java11;
      export PATH=$PATH:/c/java11/bin;
    fi

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      ./gradlew.bat --no-daemon test;
    else
      ./gradlew test;
    fi
